### PR TITLE
Update deploy.yml

### PR DESCRIPTION
**Pull request by plinss**
Skip manifest when updating bikeshed data

### CODE REVIEW

**Review by alice — APPROVED** [review]

**Review by torgo — APPROVED** [review]

**Comment by dbaron** [comment]
I'm wondering whether we'd be able to revert this.  It makes the deploy automation *much* slower.

Do you remember why we had to do this?  Was it to fix a transient issue?

**Comment by plinss** [comment]
We can try. At the time, the manifest data was out of sync (as happens from time to time when Tab's generation system falls over) and the deploy was failing. This way is certainly much slower, but it always gets the correct data.

**Comment by plinss** [comment]
The other approach we can use is to simply curl to the Bikeshed service API on https://api.csswg.org/bikeshed. It always has up to date Bikeshed code and spec data and skips all the local installation entirely.

**Comment by dbaron** [comment]
(We might also try https://github.com/marketplace/actions/spec-prod... although I'm not sure which way it runs bikeshed.)

**Comment by plinss** [comment]
Looks like spec-prod installs a local copy of Bikeshed and uses the manifest update. On the plus side, it also has auto-publishing and validation (and is maintained by someone else).

**Pull request merged**
