### PR TITLE
Update principle on HTTP usage

### PR DESCRIPTION
**Pull request by martinthomson**
The existing one is dated.  Most of that advice is now in RFC 9205.

There is also more general advice in that document, so the guidance here gets more complex as a result.

***
<a href="https://pr-preview.s3.amazonaws.com/martinthomson/design-principles/pull/487.html" title="Last updated on Apr 5, 2024, 10:31 AM UTC (7fc9d5b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/487/12d02ab...martinthomson:7fc9d5b.html" title="Last updated on Apr 5, 2024, 10:31 AM UTC (7fc9d5b)">Diff</a>

### CODE REVIEW

**Review by annevk — COMMENTED** [review]
I think we should continue having the advice that new headers should use structured fields.

**Comment by martinthomson** [comment]
That's included by reference.  See https://datatracker.ietf.org/doc/html/rfc9205#section-4.7 I don't want to duplicate that advice here.

**Comment by annevk** [comment]
I wouldn't mind redundancy on that particular requirement as for pretty much every new header that's come up in the last couple years folks had to be reminded, but okay.

**Review by LeaVerou — APPROVED** [review]

**Review by torgo — APPROVED** [review]
lgtm

**Pull request merged**
