### PR TITLE
Fix lint issues

### PR DESCRIPTION
**Pull request by gibson042**
As observed in failure of the [latest deploy job](https://github.com/w3ctag/design-principles/actions/runs/3795480809/jobs/6454644278):
> ```
> bikeshed --die-on=fatal spec index.bs build/index.html
> LINT: Your document appears to use spaces to indent, but line 795 starts with tabs.
> LINT: Your document appears to use spaces to indent, but line 796 starts with tabs.
> LINT: Your document appears to use spaces to indent, but line 797 starts with tabs.
> LINT: Your document appears to use spaces to indent, but line 798 starts with tabs.
> LINT: Your document appears to use spaces to indent, but line 799 starts with tabs.
> LINT: Your document appears to use spaces to indent, but line 803 starts with tabs.
> LINT: Your document appears to use spaces to indent, but line 804 starts with tabs.
> LINT: Your document appears to use spaces to indent, but line 811 starts with tabs.
> LINT: Your document appears to use spaces to indent, but line 812 starts with tabs.
> LINT: Your document appears to use spaces to indent, but line 813 starts with tabs.
> LINT: Your document appears to use spaces to indent, but line 814 starts with tabs.
> LINT: Your document appears to use spaces to indent, but line 815 starts with tabs.
> LINT: Your document appears to use spaces to indent, but line 816 starts with tabs.
> LINT: Your document appears to use spaces to indent, but line 817 starts with tabs.
> LINT: Your document appears to use spaces to indent, but line 818 starts with tabs.
> LINT: Your document appears to use spaces to indent, but line 819 starts with tabs.
> LINT: Your document appears to use spaces to indent, but line 820 starts with tabs.
> LINT: Your document appears to use spaces to indent, but line 821 starts with tabs.
> FATAL ERROR: Line 703 isn't indented enough (needs 1 indent) to be valid Markdown:
> "  (e.g. sends information to a document)"
>  ✘  Did not generate, due to fatal errors

***
<a href="https://pr-preview.s3.amazonaws.com/gibson042/design-principles/pull/413.html" title="Last updated on Feb 7, 2023, 8:34 PM UTC (845893b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/413/c5e4fea...gibson042:845893b.html" title="Last updated on Feb 7, 2023, 8:34 PM UTC (845893b)">Diff</a>

### CODE REVIEW

**Comment by cynthia** [comment]
Thank you for the submission - we realized that we have some consistency issues across our repositories, and we'd like to first only address the fatal errors if possible (as the formatting changes would likely clobber them).

I'm happy to do that, let us know if you can send in a revised PR.

**Comment by gibson042** [comment]
Isn't that _this_ PR? What changes are you looking for?

**Comment by LeaVerou** [comment]
> Isn't that _this_ PR? What changes are you looking for?

This PR includes a fix for the fatal error, as well as formatting changes from tabs to spaces. We have no resolution about the type of indentation we want to use (which is why the inconsistency happened in the first place). We should probably decide on that first before we fix the inconsistency one way or the other.
Regardless, the indentation changes were also proposed by #405, so if you could remove them from this one so we can merge the fix to the fatal error, that would be helpful (although the same fix is included in #408, which may end up getting merged first)

**Comment by gibson042** [comment]
@cynthia @LeaVerou OK, done.

**Review by cynthia — APPROVED** [review]

**Pull request merged**
